<a href="https://colab.research.google.com/github/alfajrii/retail-sales-analysis-python/blob/main/Copy_of_KarirNex_Python_Short_Class_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🌶️ Short Class Python - Hari 1
## "Hari Pertama Kerja di Toko Rempah & Bumbu Wangi Nusantara"

Selamat datang lagi! Kelas ini kelanjutan dari Bootcamp Data Analyst kemarin, jadi kita nggak bakal ngulang dasar-dasar Python dan pandas dari nol lagi. Kalau ada yang lupa soal variabel, list, dict, atau dasar DataFrame (`head()`, `info()`, `describe()`), tonton lagi rekaman sesi sebelumnya dulu ya..

Karena ini kelas lanjutan, hari ini kita bakal langsung tancap gas ke teknik-teknik pandas yang lebih dalam, bukan sekadar ngulang yang basic.

---

### 📖 Ceritanya begini...

Kamu baru aja diterima kerja part-time sebagai **Data Analyst** di **Toko Rempah & Bumbu Wangi Nusantara**, toko rempah dan bumbu dapur di Bandung. Pemiliknya, **Teh Rina**, udah jualan hampir setahun, baik lewat toko fisik maupun aplikasi pesan-antar.

Teh Rina udah denger kamu jago pandas dari bootcamp kemarin, jadi kali ini dia langsung kasih pertanyaan-pertanyaan yang lebih spesifik dan detail, bukan cuma "berapa total penjualan" doang.

Data transaksinya bisa kamu lihat di sini:

🔗 [https://docs.google.com/spreadsheets/d/1hmH7aVkADkHk3Un8rxGYFb4Xail0sWbK/edit?usp=drivesdk&ouid=106485154383908444810&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/1hmH7aVkADkHk3Un8rxGYFb4Xail0sWbK/edit?usp=drivesdk&ouid=106485154383908444810&rtpof=true&sd=true)

Yuk gas, kita mulai!

---
## 1. Kilas Balik Kilat

Super singkat aja ya, karena kalian udah dapat rekamannya:

- `pd.read_csv()` buat load data, `df.head()` / `df.info()` / `df.describe()` buat kenalan awal
- `df.isnull().sum()` dan `df.duplicated().sum()` buat cek data kosong dan duplikat
- `df.groupby("kolom")["kolom_lain"].sum()` buat ringkasan per kategori

Kalau ada yang masih blank soal poin-poin di atas, sempatkan tonton ulang rekamannya ya. Sekarang kita langsung load data dan gas ke materi baru.

In [ ]:
import pandas as pd
import numpy as np

url_data = "https://docs.google.com/spreadsheets/d/1hmH7aVkADkHk3Un8rxGYFb4Xail0sWbK/export?format=csv"
df = pd.read_csv(url_data)
df["sales_date"] = pd.to_datetime(df["sales_date"])
df['distance_km'] = df['distance_km'].str.replace(',', '.').astype(float)
df['discount'] = df['discount'].str.replace(',', '.').astype(float)

print("Data berhasil di-load!")
print("Jumlah baris dan kolom:", df.shape)
df.head()

Data berhasil di-load!
Jumlah baris dan kolom: (10000, 16)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.0,9000,0,9000,completed
1,2025-09-11,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur,Rempah & Sayuran Segar,250 gr,8000,1,Beli di Toko,0.0,0.0,8000,0,8000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.0,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.0,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.0,20000,0,20000,completed

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sales_date        10000 non-null  datetime64[ns]
 1   order_id          10000 non-null  object
 2   customer_name     10000 non-null  object
 3   customer_address  10000 non-null  object
 4   product_name      10000 non-null  object
 5   category          10000 non-null  object
 6   unit              10000 non-null  object
 7   price             10000 non-null  int64
 8   quantity          10000 non-null  int64
 9   order_type        10000 non-null  object
 10  distance_km       10000 non-null  float64
 11  discount          10000 non-null  float64
 12  total             10000 non-null  int64
 13  shipping_fee      10000 non-null  int64
 14  total_sales       10000 non-null  int64
 15  status            10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(8)
memory usage: 1.2+ MB

In [ ]:
df.discount.unique()

array(['0', '0,05', '0,1'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sales_date        10000 non-null  datetime64[ns]
 1   order_id          10000 non-null  object
 2   customer_name     10000 non-null  object
 3   customer_address  10000 non-null  object
 4   product_name      10000 non-null  object
 5   category          10000 non-null  object
 6   unit              10000 non-null  object
 7   price             10000 non-null  int64
 8   quantity          10000 non-null  int64
 9   order_type        10000 non-null  object
 10  distance_km       10000 non-null  float64
 11  discount          10000 non-null  float64
 12  total             10000 non-null  int64
 13  shipping_fee      10000 non-null  int64
 14  total_sales       10000 non-null  int64
 15  status            10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(8)
memory usage: 1.2+ MB

### Cek cepat kerapian data

Sebelum lanjut, kita cek dulu sekilas: missing value, duplikat, dan konsistensi teks.

In [ ]:
df.customer_address

0             Kecamatan Cicalengka, Kabupaten Bandung
1                    Kecamatan Gedebage, Kota Bandung
2       Kecamatan Padalarang, Kabupaten Bandung Barat
3          Kecamatan Cisarua, Kabupaten Bandung Barat
4                    Kecamatan Sukajadi, Kota Bandung
                            ...
9995          Kecamatan Cicalengka, Kabupaten Bandung
9996            Kecamatan Banjaran, Kabupaten Bandung
9997    Kecamatan Padalarang, Kabupaten Bandung Barat
9998            Kecamatan Cileunyi, Kabupaten Bandung
9999              Kecamatan Astanaanyar, Kota Bandung
Name: customer_address, Length: 10000, dtype: object

In [ ]:
df.head(1)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0,0,9000,0,9000,completed

In [ ]:
sorted(df['category'].unique())

['Paket Bumbu Instan', 'Rempah & Sayuran Segar', 'Rempah Kering & Bumbu Dapur']

In [ ]:
print("Missing value:")
print(df.isnull().sum().sum(), "total sel kosong")
print("Baris duplikat:", df.duplicated().sum())
print("Kategori unik:", sorted(df["category"].unique()))
print("Order type unik:", sorted(df["order_type"].unique()))

Missing value:
0 total sel kosong
Baris duplikat: 0
Kategori unik: ['Paket Bumbu Instan', 'Rempah & Sayuran Segar', 'Rempah Kering & Bumbu Dapur']
Order type unik: ['Beli di Toko', 'Diantar (Aplikasi Toko)']

Oke, datanya bersih. Sekarang kita masuk ke teknik-teknik pandas yang lebih dalam.

---
## 2. DataFrame: Selecting & Transforming Data

### 2.1 `.loc[]`: Filter Baris + Pilih Kolom Sekaligus

Kalau di bootcamp kemarin kita udah belajar filter pakai `df[df["kolom"] == nilai]`, sekarang kita kenalan sama `.loc[]`, yang bisa filter baris DAN milih kolom tertentu dalam satu langkah, formatnya `df.loc[kondisi, ["kolom1", "kolom2"]]`.

In [ ]:
df[df.total_sales > 150000].head(1)

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
123,2025-08-02,RMP00124,Customer_1190,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Sambal Hijau,Paket Bumbu Instan,1 paket,32000,5,Diantar (Aplikasi Toko),"2,2",0,160000,9000,169000,completed

In [ ]:
trx_besar = df.loc[
    df.total_sales > 150000,
    ['order_id','product_name', 'unit', 'order_type']
]

In [ ]:
trx_besar

      order_id                product_name     unit               order_type
123   RMP00124    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
145   RMP00146           Paket Bumbu Pecel  1 paket  Diantar (Aplikasi Toko)
364   RMP00365       Paket Bumbu Rica-Rica  1 paket             Beli di Toko
617   RMP00618   Paket Bumbu Coto Makassar  1 paket  Diantar (Aplikasi Toko)
626   RMP00627     Paket Bumbu Sate Padang  1 paket  Diantar (Aplikasi Toko)
941   RMP00942    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
1116  RMP01117      Paket Bumbu Sayur Asem  1 paket  Diantar (Aplikasi Toko)
1300  RMP01301    Paket Bumbu Pindang Ikan  1 paket  Diantar (Aplikasi Toko)
1384  RMP01385    Paket Bumbu Sambal Hijau  1 paket             Beli di Toko
2024  RMP02025       Paket Bumbu Rica-Rica  1 paket  Diantar (Aplikasi Toko)
2227  RMP02228    Paket Bumbu Pindang Ikan  1 paket  Diantar (Aplikasi Toko)
2253  RMP02254   Paket Bumbu Ketupat Sayur  1 paket  Diantar (Aplikasi Toko)
2301  RMP02302    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
2685  RMP02686           Paket Bumbu Pecel  1 paket  Diantar (Aplikasi Toko)
2713  RMP02714   Paket Bumbu Ketupat Sayur  1 paket  Diantar (Aplikasi Toko)
2727  RMP02728   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
2943  RMP02944           Paket Bumbu Pecel  1 paket  Diantar (Aplikasi Toko)
3303  RMP03304    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
3572  RMP03573   Paket Bumbu Ketupat Sayur  1 paket  Diantar (Aplikasi Toko)
3663  RMP03664           Paket Bumbu Merah  1 paket  Diantar (Aplikasi Toko)
4585  RMP04586  Paket Bumbu Kerupuk Sambal  1 paket  Diantar (Aplikasi Toko)
4598  RMP04599    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
4779  RMP04780    Paket Bumbu Sambal Hijau  1 paket             Beli di Toko
4898  RMP04899   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
5348  RMP05349   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
5382  RMP05383   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
5945  RMP05946    Paket Bumbu Sambal Hijau  1 paket             Beli di Toko
6058  RMP06059    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
6170  RMP06171           Paket Bumbu Merah  1 paket  Diantar (Aplikasi Toko)
6493  RMP06494    Paket Bumbu Semur Daging  1 paket  Diantar (Aplikasi Toko)
6846  RMP06847    Paket Bumbu Sambal Hijau  1 paket  Diantar (Aplikasi Toko)
6974  RMP06975   Paket Bumbu Coto Makassar  1 paket  Diantar (Aplikasi Toko)
7121  RMP07122   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
7188  RMP07189    Paket Bumbu Sambal Hijau  1 paket             Beli di Toko
8076  RMP08077       Paket Bumbu Rica-Rica  1 paket             Beli di Toko
8341  RMP08342   Paket Bumbu Coto Makassar  1 paket             Beli di Toko
8427  RMP08428      Paket Bumbu Sayur Asem  1 paket  Diantar (Aplikasi Toko)
8623  RMP08624    Paket Bumbu Pindang Ikan  1 paket  Diantar (Aplikasi Toko)
9280  RMP09281   Paket Bumbu Ketupat Sayur  1 paket  Diantar (Aplikasi Toko)

In [ ]:
# ambil transaksi dengan total_sales di atas 150.000, tapi cuma tampilkan kolom yang relevan
transaksi_besar = df.loc[
    df["total_sales"] > 150000,
    ["order_id", "product_name", "category", "total_sales"]
]

print("Jumlah transaksi:", len(transaksi_besar))
transaksi_besar.head()

### 2.2 `.iloc[]`: Ambil Baris/Kolom Berdasarkan Posisi

Kalau `.loc[]` pakai nama kolom dan kondisi, `.iloc[]` pakai **posisi urutan** (index angka), mirip cara kamu ambil item dari list.

In [ ]:
#        start:stop(n-1):step
df.iloc[0:5,0:3]
#   0              1          2                  3

  sales_date  order_id  customer_name
0 2025-07-17  RMP00001  Customer_1198
1 2025-09-11  RMP00002  Customer_3969
2 2025-11-15  RMP00003   Customer_575
3 2025-06-06  RMP00004  Customer_1394
4 2025-12-13  RMP00005  Customer_1382

In [ ]:
# ambil baris ke-0 sampai ke-2 (3 baris pertama), dan kolom ke-1 sampai ke-4
df.iloc[0:3, 1:5]

In [ ]:
df[['order_id','unit','price']]

      order_id     unit  price
0     RMP00001    50 gr   9000
1     RMP00002   250 gr   8000
2     RMP00003  1 paket  15000
3     RMP00004  1 paket  22000
4     RMP00005  1 paket  20000
...        ...      ...    ...
9995  RMP09996  1 paket  17000
9996  RMP09997    50 gr   9000
9997  RMP09998  1 paket  14000
9998  RMP09999  1 paket  32000
9999  RMP10000  1 paket  28000

[10000 rows x 3 columns]

In [ ]:
df[df.total_sales > 150000][['order_id','unit','price']]

      order_id     unit  price
123   RMP00124  1 paket  32000
145   RMP00146  1 paket  28000
364   RMP00365  1 paket  32000
617   RMP00618  1 paket  32000
626   RMP00627  1 paket  28000
941   RMP00942  1 paket  32000
1116  RMP01117  1 paket  28000
1300  RMP01301  1 paket  25000
1384  RMP01385  1 paket  32000
2024  RMP02025  1 paket  32000
2227  RMP02228  1 paket  25000
2253  RMP02254  1 paket  28000
2301  RMP02302  1 paket  32000
2685  RMP02686  1 paket  28000
2713  RMP02714  1 paket  28000
2727  RMP02728  1 paket  32000
2943  RMP02944  1 paket  28000
3303  RMP03304  1 paket  32000
3572  RMP03573  1 paket  28000
3663  RMP03664  1 paket  28000
4585  RMP04586  1 paket  28000
4598  RMP04599  1 paket  32000
4779  RMP04780  1 paket  32000
4898  RMP04899  1 paket  32000
5348  RMP05349  1 paket  32000
5382  RMP05383  1 paket  32000
5945  RMP05946  1 paket  32000
6058  RMP06059  1 paket  32000
6170  RMP06171  1 paket  28000
6493  RMP06494  1 paket  28000
6846  RMP06847  1 paket  32000
6974  RMP06975  1 paket  32000
7121  RMP07122  1 paket  32000
7188  RMP07189  1 paket  32000
8076  RMP08077  1 paket  32000
8341  RMP08342  1 paket  32000
8427  RMP08428  1 paket  28000
8623  RMP08624  1 paket  25000
9280  RMP09281  1 paket  28000

### 2.3 Filtering Majemuk: `.isin()` dan `.between()`

Dua fungsi ini bikin filtering yang tadinya ribet (banyak `|` dan `&`) jadi lebih ringkas.

`.isin()` buat cek apakah nilai ada di dalam sebuah list:

In [ ]:
kategori_dicari = ["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"]
df[df['category'].isin(["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"])]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0,0,9000,0,9000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),"14,2",0,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0,0,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),"1,5",0,20000,0,20000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),"7,8","0,05",53200,13000,66200,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0,"0,1",30600,0,30600,completed
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),"20,4",0,27000,32000,59000,cancelled
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),"10,9",0,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),"12,5",0,32000,25000,57000,completed
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0,0,56000,0,56000,completed

In [ ]:
df[(df.category == "Paket Bumbu Instan") | (df.category == "Rempah Kering & Bumbu Dapur")]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0,0,9000,0,9000,completed
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),"14,2",0,30000,25000,55000,completed
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0,0,22000,0,22000,completed
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),"1,5",0,20000,0,20000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),"7,8","0,05",53200,13000,66200,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0,"0,1",30600,0,30600,completed
9996,2025-04-12,RMP09997,Customer_1357,"Kecamatan Banjaran, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,3,Diantar (Aplikasi Toko),"20,4",0,27000,32000,59000,cancelled
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),"10,9",0,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),"12,5",0,32000,25000,57000,completed
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0,0,56000,0,56000,completed

In [ ]:
# ambil transaksi dari 2 kategori sekaligus, tanpa perlu nulis kondisi | berkali-kali
kategori_dicari = ["Paket Bumbu Instan", "Rempah Kering & Bumbu Dapur"]
hasil_isin = df[df["category"].isin(kategori_dicari)]

print("Jumlah transaksi:", len(hasil_isin))

`.between()` buat cek apakah nilai ada di dalam suatu rentang:

In [ ]:
df[df["distance_km"].between(5,15)]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
6,2025-09-05,RMP00007,Customer_2026,"Kecamatan Majalaya, Kabupaten Bandung",Jahe,Rempah & Sayuran Segar,250 gr,9000,2,Diantar (Aplikasi Toko),14.6,0.00,18000,25000,43000,completed
12,2025-04-06,RMP00013,Customer_3323,"Kecamatan Dayeuhkolot, Kabupaten Bandung",Daun Kemangi,Rempah & Sayuran Segar,100 gr,4000,1,Diantar (Aplikasi Toko),11.4,0.00,4000,18000,22000,completed
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2025-11-16,RMP09992,Customer_1478,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Gulai Ikan,Paket Bumbu Instan,1 paket,17000,1,Diantar (Aplikasi Toko),9.7,0.00,17000,18000,35000,completed
9992,2025-01-13,RMP09993,Customer_1585,"Kecamatan Lembang, Kabupaten Bandung Barat",Gula Merah,Rempah Kering & Bumbu Dapur,500 gr,13000,1,Diantar (Aplikasi Toko),10.1,0.00,13000,18000,31000,completed
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),14.9,0.00,15000,25000,40000,completed
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed

In [ ]:
df[(df["distance_km"]>= 5) & (df["distance_km"]<= 15)]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.00,30000,25000,55000,completed
5,2025-09-09,RMP00006,Customer_1979,"Kecamatan Cibiru, Kota Bandung",Paket Bumbu Kerupuk Sambal,Paket Bumbu Instan,1 paket,28000,2,Diantar (Aplikasi Toko),7.8,0.05,53200,13000,66200,completed
6,2025-09-05,RMP00007,Customer_2026,"Kecamatan Majalaya, Kabupaten Bandung",Jahe,Rempah & Sayuran Segar,250 gr,9000,2,Diantar (Aplikasi Toko),14.6,0.00,18000,25000,43000,completed
12,2025-04-06,RMP00013,Customer_3323,"Kecamatan Dayeuhkolot, Kabupaten Bandung",Daun Kemangi,Rempah & Sayuran Segar,100 gr,4000,1,Diantar (Aplikasi Toko),11.4,0.00,4000,18000,22000,completed
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2025-11-16,RMP09992,Customer_1478,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Gulai Ikan,Paket Bumbu Instan,1 paket,17000,1,Diantar (Aplikasi Toko),9.7,0.00,17000,18000,35000,completed
9992,2025-01-13,RMP09993,Customer_1585,"Kecamatan Lembang, Kabupaten Bandung Barat",Gula Merah,Rempah Kering & Bumbu Dapur,500 gr,13000,1,Diantar (Aplikasi Toko),10.1,0.00,13000,18000,31000,completed
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),14.9,0.00,15000,25000,40000,completed
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.00,14000,18000,32000,completed
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.00,32000,25000,57000,completed

In [ ]:
# cari transaksi dengan jarak antar antara 5 sampai 15 km
jarak_menengah = df[df["distance_km"].between(5, 15)]

print("Jumlah transaksi dengan jarak 5-15 km:", len(jarak_menengah))

Jumlah transaksi dengan jarak 5-15 km: 2474

### 2.4 `.apply()` + `lambda`: Bikin Kolom Baru dari Logika Custom

`.apply()` dipakai buat menjalankan sebuah fungsi ke setiap nilai di suatu kolom. Kita bisa pakai function biasa (`def`), atau kalau logikanya simpel dan cuma dipakai sekali, bisa pakai `lambda` (function tanpa nama, ditulis dalam satu baris).

In [ ]:
def klasifikasi_transaksi(nilai):
    if nilai < 20000:
        return "Kecil"
    elif nilai <= 60000:
        return "Sedang"
    else:
        return "Besar"

df["segmen_transaksi"] = df["total_sales"].apply(klasifikasi_transaksi)

# contoh versi lambda untuk logika yang lebih simpel: kasih tanda transaksi yang pakai diskon
df["ada_diskon"] = df["discount"].apply(lambda x: "Ya" if x > 0 else "Tidak")

df[["total_sales", "segmen_transaksi", "discount", "ada_diskon"]].head()

   total_sales segmen_transaksi  discount ada_diskon
0         9000            Kecil       0.0      Tidak
1         8000            Kecil       0.0      Tidak
2        55000           Sedang       0.0      Tidak
3        22000           Sedang       0.0      Tidak
4        20000           Sedang       0.0      Tidak

In [ ]:
df['discount'].apply(lambda x:"Ya" if x > 0 else "Tidak")

0       Tidak
1       Tidak
2       Tidak
3       Tidak
4       Tidak
        ...
9995       Ya
9996    Tidak
9997    Tidak
9998    Tidak
9999    Tidak
Name: discount, Length: 10000, dtype: object

In [ ]:
def klasifikasi_transaksi(nilai):
    if nilai < 20000:
        return "Kecil"
    elif nilai <= 60000:
        return "Sedang"
    else:
        return "Besar"

In [ ]:
df['segmen_transaksi'] = df['total_sales'].apply(klasifikasi_transaksi)
df.head()

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status,segmen_transaksi
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.0,9000,0,9000,completed,Kecil
1,2025-09-11,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur,Rempah & Sayuran Segar,250 gr,8000,1,Beli di Toko,0.0,0.0,8000,0,8000,completed,Kecil
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.0,30000,25000,55000,completed,Sedang
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.0,22000,0,22000,completed,Sedang
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.0,20000,0,20000,completed,Sedang

In [ ]:
klasifikasi_transaksi(55000)

'Sedang'

---
## 3. Data Cleaning: Outlier & String Methods

### 3.1 Deteksi Outlier Pakai Metode IQR

Selain cek missing value dan duplikat, cleaning yang lebih dalam juga perlu cek **outlier**, yaitu nilai yang jauh banget beda dari kebanyakan data, bisa jadi kesalahan input, bisa juga transaksi yang memang wajar tapi ekstrem.

Salah satu metode yang umum dipakai adalah **IQR (Interquartile Range)**: hitung Q1 (persentil 25) dan Q3 (persentil 75), lalu nilai di luar rentang `Q1 - 1.5×IQR` sampai `Q3 + 1.5×IQR` dianggap outlier.

In [ ]:
IQR

np.float64(34000.0)

In [ ]:
transaksi_selesai = df[df["status"] == "completed"].copy()

Q1 = transaksi_selesai["total_sales"].quantile(0.25)
Q3 = transaksi_selesai["total_sales"].quantile(0.75)
IQR = Q3 - Q1
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

print(f"Q1: {Q1:,.0f} | Q3: {Q3:,.0f} | IQR: {IQR:,.0f}")
print(f"Batas atas outlier: {batas_atas:,.0f}")

outlier = transaksi_selesai[transaksi_selesai["total_sales"] > batas_atas]
print("Jumlah transaksi outlier:", len(outlier))
print(f"Total pendapatan dari transaksi outlier: Rp {outlier['total_sales'].sum():,.0f}".replace(",", "."))

Q1: 19,000 | Q3: 53,000 | IQR: 34,000
Batas atas outlier: 104,000
Jumlah transaksi outlier: 304
Total pendapatan dari transaksi outlier: Rp 38.407.250

In [ ]:
transaksi_selesai[transaksi_selesai["total_sales"] < batas_bawah]

Empty DataFrame
Columns: [sales_date, order_id, customer_name, customer_address, product_name, category, unit, price, quantity, order_type, distance_km, discount, total, shipping_fee, total_sales, status, segmen_transaksi, ada_diskon]
Index: []

**Penting:** outlier itu nggak otomatis berarti "data salah". Di kasus kita ini kemungkinan besar itu transaksi pembelian dalam jumlah besar yang memang valid (misalnya buat acara atau reseller), bukan kesalahan input. Makanya, ketemu outlier itu bukan otomatis dihapus, tapi jadi bahan buat digali lebih lanjut.

### 3.2 String Methods Lanjutan

Kita udah pernah pakai `str.extract()` buat ambil kecamatan. Sekarang kenalan sama dua fungsi string lain yang sering kepake.

`.str.contains()` buat cek apakah suatu teks mengandung kata tertentu:

In [ ]:
# cari semua transaksi dari pelanggan yang alamatnya mengandung kata "Cimahi"
pelanggan_cimahi = df[df["customer_address"].str.contains("Cimahi")]

print("Jumlah transaksi dari area Cimahi:", len(pelanggan_cimahi))

Jumlah transaksi dari area Cimahi: 1019

In [ ]:
df[df["customer_address"].str.contains("Cimahi")]

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status,segmen_transaksi,ada_diskon
14,2025-12-30,RMP00015,Customer_3247,"Kecamatan Cimahi Tengah, Kota Cimahi",Merica Hitam,Rempah Kering & Bumbu Dapur,100 gr,13000,1,Diantar (Aplikasi Toko),7.1,0.00,13000,13000,26000,completed,Sedang,Tidak
21,2025-09-20,RMP00022,Customer_3671,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Tumis Kangkung,Paket Bumbu Instan,1 paket,25000,3,Diantar (Aplikasi Toko),5.1,0.00,75000,13000,88000,completed,Besar,Tidak
27,2025-02-25,RMP00028,Customer_652,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,3,Beli di Toko,0.0,0.00,45000,0,45000,refund,Sedang,Tidak
39,2025-03-24,RMP00040,Customer_1527,"Kecamatan Cimahi Selatan, Kota Cimahi",Pala,Rempah Kering & Bumbu Dapur,100 gr,15000,1,Beli di Toko,0.0,0.00,15000,0,15000,completed,Kecil,Tidak
43,2025-12-14,RMP00044,Customer_4046,"Kecamatan Cimahi Tengah, Kota Cimahi",Paket Bumbu Sambal Matah,Paket Bumbu Instan,1 paket,22000,3,Beli di Toko,0.0,0.05,62700,0,62700,completed,Besar,Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9922,2025-05-01,RMP09923,Customer_3652,"Kecamatan Cimahi Selatan, Kota Cimahi",Jahe,Rempah & Sayuran Segar,250 gr,9000,2,Beli di Toko,0.0,0.00,18000,0,18000,completed,Kecil,Tidak
9965,2025-04-04,RMP09966,Customer_3684,"Kecamatan Cimahi Selatan, Kota Cimahi",Cabai Merah Keriting,Rempah & Sayuran Segar,250 gr,15000,2,Diantar (Aplikasi Toko),10.9,0.05,28500,18000,46500,completed,Sedang,Ya
9971,2025-10-03,RMP09972,Customer_612,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Semur Daging,Paket Bumbu Instan,1 paket,28000,3,Diantar (Aplikasi Toko),5.7,0.00,84000,13000,97000,completed,Besar,Tidak
9985,2025-09-22,RMP09986,Customer_3359,"Kecamatan Cimahi Selatan, Kota Cimahi",Pala,Rempah Kering & Bumbu Dapur,100 gr,15000,2,Beli di Toko,0.0,0.00,30000,0,30000,completed,Sedang,Tidak
9991,2025-11-16,RMP09992,Customer_1478,"Kecamatan Cimahi Selatan, Kota Cimahi",Paket Bumbu Gulai Ikan,Paket Bumbu Instan,1 paket,17000,1,Diantar (Aplikasi Toko),9.7,0.00,17000,18000,35000,completed,Sedang,Tidak

`.str.split()` buat memecah teks jadi beberapa bagian berdasarkan pemisah tertentu (mirip `split()` di Python biasa, tapi versi pandas, bisa langsung diterapkan ke seluruh kolom):

In [ ]:
# pecah customer_address jadi 2 bagian: kecamatan dan kota/kabupaten, pakai tanda koma sebagai pemisah
alamat_terpisah = df["customer_address"].str.split(",", expand=True)
alamat_terpisah.columns = ["kecamatan_raw", "kota_kabupaten_raw"]

df["kecamatan"] = alamat_terpisah["kecamatan_raw"].str.replace("Kecamatan ", "", regex=False).str.strip()
df["kota_kabupaten"] = alamat_terpisah["kota_kabupaten_raw"].str.strip()

df[["customer_address", "kecamatan", "kota_kabupaten"]].head()

,customer_address,kecamatan,kota_kabupaten
0,"Kecamatan Cicalengka, Kabupaten Bandung",Cicalengka,Kabupaten Bandung
1,"Kecamatan Gedebage, Kota Bandung",Gedebage,Kota Bandung
2,"Kecamatan Padalarang, Kabupaten Bandung Barat",Padalarang,Kabupaten Bandung Barat
3,"Kecamatan Cisarua, Kabupaten Bandung Barat",Cisarua,Kabupaten Bandung Barat
4,"Kecamatan Sukajadi, Kota Bandung",Sukajadi,Kota Bandung

In [ ]:
alamat_terpisah = df["customer_address"].str.split(",", expand = True)
alamat_terpisah.columns = ["kecamatan_raw", "kota_kabupaten_raw"]

alamat_terpisah['kecamatan_raw'].str.replace("Kecamatan ", "").str.strip()

0        Cicalengka
1          Gedebage
2        Padalarang
3           Cisarua
4          Sukajadi
           ...
9995     Cicalengka
9996       Banjaran
9997     Padalarang
9998       Cileunyi
9999    Astanaanyar
Name: kecamatan_raw, Length: 10000, dtype: object

---
## 4. GroupBy: Agregasi Ganda, Transform, dan Rank

### 4.1 `.agg()` dengan Banyak Fungsi Sekaligus

Kemarin kita cuma pakai satu fungsi agregasi tiap kali (`.sum()` atau `.mean()` sendiri-sendiri). Sekarang kita bisa hitung beberapa sekaligus pakai `.agg()`.

In [ ]:
transaksi_selesai = df[df["status"] == "completed"].copy()

ringkasan_kategori = transaksi_selesai.groupby("category")["total_sales"].agg(["sum", "mean", "count"])
ringkasan_kategori.columns = ["total_pendapatan", "rata_rata_pendapatan", "jumlah_transaksi"]
ringkasan_kategori.round(0)

In [ ]:
ringkasan_kategori = transaksi_selesai.groupby("category")['total_sales'].agg(['sum','mean','count'])
ringkasan_kategori.columns = ['total_pendapatan','rata_rata_pendapatan','jumlah_transaksi']
ringkasan_kategori.reset_index()

,category,total_pendapatan,rata_rata_pendapatan,jumlah_transaksi
0,Paket Bumbu Instan,264921050,48860.392844,5422
1,Rempah & Sayuran Segar,45158175,25242.132476,1789
2,Rempah Kering & Bumbu Dapur,47567075,26455.547831,1798

### 4.2 `.transform()`: Bandingkan Tiap Baris dengan Rata-Rata Grupnya

`groupby().sum()` atau `.mean()` biasa itu hasilnya **meringkas** data (dari 9000 baris jadi cuma 3 baris kategori). Tapi kadang kita mau tetap punya 9000 baris itu, cuma nambahin kolom "rata-rata kategorinya berapa" di tiap baris. Nah, itu gunanya `.transform()`.

In [ ]:
display(transaksi_selesai.groupby("category")["total_sales"].mean())

transaksi_selesai["rata2_kategori"] = transaksi_selesai.groupby("category")["total_sales"].transform("mean")
transaksi_selesai

category
Paket Bumbu Instan             48860.392844
Rempah & Sayuran Segar         25242.132476
Rempah Kering & Bumbu Dapur    26455.547831
Name: total_sales, dtype: float64

,sales_date,order_id,customer_name,customer_address,product_name,category,unit,price,quantity,order_type,distance_km,discount,total,shipping_fee,total_sales,status,segmen_transaksi,ada_diskon,rata2_kategori
0,2025-07-17,RMP00001,Customer_1198,"Kecamatan Cicalengka, Kabupaten Bandung",Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,50 gr,9000,1,Beli di Toko,0.0,0.0,9000,0,9000,completed,Kecil,Tidak,26455.547831
1,2025-09-11,RMP00002,Customer_3969,"Kecamatan Gedebage, Kota Bandung",Kencur,Rempah & Sayuran Segar,250 gr,8000,1,Beli di Toko,0.0,0.0,8000,0,8000,completed,Kecil,Tidak,25242.132476
2,2025-11-15,RMP00003,Customer_575,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Gule Sapi,Paket Bumbu Instan,1 paket,15000,2,Diantar (Aplikasi Toko),14.2,0.0,30000,25000,55000,completed,Sedang,Tidak,48860.392844
3,2025-06-06,RMP00004,Customer_1394,"Kecamatan Cisarua, Kabupaten Bandung Barat",Paket Bumbu Soto Betawi,Paket Bumbu Instan,1 paket,22000,1,Beli di Toko,0.0,0.0,22000,0,22000,completed,Sedang,Tidak,48860.392844
4,2025-12-13,RMP00005,Customer_1382,"Kecamatan Sukajadi, Kota Bandung",Paket Bumbu Woku Manado,Paket Bumbu Instan,1 paket,20000,1,Diantar (Aplikasi Toko),1.5,0.0,20000,0,20000,completed,Sedang,Tidak,48860.392844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2025-09-17,RMP09995,Customer_3219,"Kecamatan Ngamprah, Kabupaten Bandung Barat",Paket Bumbu Kari Ayam,Paket Bumbu Instan,1 paket,15000,1,Diantar (Aplikasi Toko),14.9,0.0,15000,25000,40000,completed,Sedang,Tidak,48860.392844
9995,2025-05-19,RMP09996,Customer_427,"Kecamatan Cicalengka, Kabupaten Bandung",Paket Bumbu Nasi Goreng,Paket Bumbu Instan,1 paket,17000,2,Beli di Toko,0.0,0.1,30600,0,30600,completed,Sedang,Ya,48860.392844
9997,2025-01-02,RMP09998,Customer_3176,"Kecamatan Padalarang, Kabupaten Bandung Barat",Paket Bumbu Tongseng,Paket Bumbu Instan,1 paket,14000,1,Diantar (Aplikasi Toko),10.9,0.0,14000,18000,32000,completed,Sedang,Tidak,48860.392844
9998,2025-12-26,RMP09999,Customer_730,"Kecamatan Cileunyi, Kabupaten Bandung",Paket Bumbu Rica-Rica,Paket Bumbu Instan,1 paket,32000,1,Diantar (Aplikasi Toko),12.5,0.0,32000,25000,57000,completed,Sedang,Tidak,48860.392844
9999,2025-10-25,RMP10000,Customer_1425,"Kecamatan Astanaanyar, Kota Bandung",Paket Bumbu Pecel,Paket Bumbu Instan,1 paket,28000,2,Beli di Toko,0.0,0.0,56000,0,56000,completed,Sedang,Tidak,48860.392844

In [ ]:
transaksi_selesai["rata2_kategori"] = (
    transaksi_selesai.groupby("category")["total_sales"].transform("mean")
)
transaksi_selesai["selisih_dari_rata2"] = (
    transaksi_selesai["total_sales"] - transaksi_selesai["rata2_kategori"]
)

transaksi_selesai[["product_name", "category", "total_sales", "rata2_kategori", "selisih_dari_rata2"]].head()

,product_name,category,total_sales,rata2_kategori,selisih_dari_rata2
0,Bunga Lawang (Pekak),Rempah Kering & Bumbu Dapur,9000,26455.547831,-17455.547831
1,Kencur,Rempah & Sayuran Segar,8000,25242.132476,-17242.132476
2,Paket Bumbu Gule Sapi,Paket Bumbu Instan,55000,48860.392844,6139.607156
3,Paket Bumbu Soto Betawi,Paket Bumbu Instan,22000,48860.392844,-26860.392844
4,Paket Bumbu Woku Manado,Paket Bumbu Instan,20000,48860.392844,-28860.392844

Kolom `selisih_dari_rata2` ini berguna banget buat cari transaksi yang jauh di atas atau di bawah kebiasaan kategorinya, kita pakai ini di case study nanti.

### 4.3 `.rank()`: Bikin Peringkat di Dalam Grup

`.rank()` dipakai buat kasih peringkat, dan kalau digabung sama `groupby()`, kita bisa bikin peringkat **di dalam masing-masing grup**, bukan peringkat keseluruhan.

In [ ]:
transaksi_selesai.groupby(["category", "product_name"])["total_sales"].sum().reset_index()

                       category             product_name  total_sales
0            Paket Bumbu Instan   Paket Bumbu Asam Padeh      3152700
1            Paket Bumbu Instan   Paket Bumbu Ayam Bakar      4406000
2            Paket Bumbu Instan  Paket Bumbu Ayam Geprek      2901200
3            Paket Bumbu Instan   Paket Bumbu Ayam Kecap      3354750
4            Paket Bumbu Instan    Paket Bumbu Ayam Rica      3637000
..                          ...                      ...          ...
95  Rempah Kering & Bumbu Dapur             Merica Putih      2905200
96  Rempah Kering & Bumbu Dapur                     Pala      3397250
97  Rempah Kering & Bumbu Dapur             Terasi Udang      2357725
98  Rempah Kering & Bumbu Dapur             Vanili Bubuk      1479500
99  Rempah Kering & Bumbu Dapur                    Wijen      2478000

[100 rows x 3 columns]

In [ ]:
pendapatan_produk.groupby("category")["total_sales"].rank(ascending=False, method="min")

0     54.0
1     27.0
2     58.0
3     45.0
4     39.0
      ...
95     4.0
96     2.0
97    10.0
98    20.0
99     8.0
Name: total_sales, Length: 100, dtype: float64

In [ ]:
# hitung total pendapatan per produk per kategori
pendapatan_produk = (
    transaksi_selesai.groupby(["category", "product_name"])["total_sales"]
    .sum()
    .reset_index()
)

# bikin ranking produk DI DALAM tiap kategori (rank 1 = pendapatan tertinggi di kategori itu)
pendapatan_produk["rank_dalam_kategori"] = (
    pendapatan_produk.groupby("category")["total_sales"]
    .rank(ascending=False, method="min")
)

pendapatan_produk.sort_values(["category", "rank_dalam_kategori"]).head(10)

,category,product_name,total_sales,rank_dalam_kategori
21,Paket Bumbu Instan,Paket Bumbu Kerupuk Sambal,6937000,1.0
39,Paket Bumbu Instan,Paket Bumbu Rica-Rica,6868000,2.0
41,Paket Bumbu Instan,Paket Bumbu Sambal Hijau,6736400,3.0
34,Paket Bumbu Instan,Paket Bumbu Pindang Ikan,6611000,4.0
22,Paket Bumbu Instan,Paket Bumbu Ketupat Sayur,6594800,5.0
10,Paket Bumbu Instan,Paket Bumbu Coto Makassar,6352200,6.0
57,Paket Bumbu Instan,Paket Bumbu Tumis Kangkung,6107750,7.0
46,Paket Bumbu Instan,Paket Bumbu Sayur Asem,5999800,8.0
28,Paket Bumbu Instan,Paket Bumbu Nasi Uduk,5962750,9.0
48,Paket Bumbu Instan,Paket Bumbu Semur Daging,5935600,10.0

---
## 5. Case Study: Laporan Detail buat Teh Rina

Sekarang, gabungin semua teknik baru yang udah kamu pelajari buat jawab pertanyaan-pertanyaan Teh Rina yang lebih spesifik.

### Pertanyaan 1: Produk apa yang jadi juara pendapatan DI MASING-MASING kategori?

*Petunjuk: pakai hasil `rank_dalam_kategori` yang udah kita bikin, ambil yang rank-nya 1.*

### Pertanyaan 2: Seberapa besar kontribusi transaksi "outlier" (pembelian besar) terhadap total pendapatan toko?

### Pertanyaan 3: Produk apa aja yang paling sering jadi transaksi "besar" (jauh di atas rata-rata kategorinya)?

*Petunjuk: urutkan berdasarkan `selisih_dari_rata2` dari yang paling besar.*

---
### 🎉 Kerja bagus hari ini!

Teh Rina kagum banget, laporan kamu sekarang jauh lebih detail dibanding sebelumnya, bukan cuma "kategori mana paling laku" tapi udah sampai level "produk juara per kategori" dan "transaksi mana yang di luar kebiasaan". Ini level analisis yang beneran dipakai di dunia kerja data analyst.

Tapi, ada kabar baru: minggu depan Teh Rina harus presentasi ke calon investor yang mau bantu dia buka cabang kedua. Dia minta laporan yang lebih lengkap, dengan **grafik dan visualisasi** yang gampang dipahami orang yang nggak ngerti data. Selain itu, ada satu data lagi yang selama ini dipegang terpisah oleh tim gudang: daftar produk lengkap dengan kategori dan harganya, yang perlu digabung ke data transaksi.

**Sampai ketemu di Hari 2, kita akan belajar gimana caranya menggabungkan data (merge), bikin visualisasi yang menarik, dan menyusun laporan yang siap dipresentasikan ke investor!**

## 📌 Tugas Hari 1

Kerjakan tugas berikut buat mengasah lagi materi hari ini:

🔗 **https://colab.research.google.com/drive/1IPXJg3dVfv35Qb9-6nDgdL9Eqwn72Nr8#scrollTo=12doxQkm2YBd**